repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
        # intentionally ignored as it symlinks into a submodule
        exclude: ^\.config/nvim/autoload/plug\.vim$
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^(\.gitignore|\.gitignore_global)$
        args: ["--unique"]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
