repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: ^(\.gitignore|\.gitignore_global)$
        args: ["--unique"]
      - id: file-contents-sorter
        files: ^\.config/nvim/after/plugin/(typos|keyword_replace)\.vim$
        args:
          - --ignore-case
          - --unique
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
