abbr Boc Box
abbr cosnt const
abbr cosntexpr constexpr
abbr costn const
abbr defualt default
abbr Degub Debug
abbr degub debug
abbr dgb dbg
abbr firend friend
abbr flase false
abbr Flase False
abbr improt import
abbr inlcude include
abbr intput input
abbr mian main
abbr retrun return
abbr strcut struct
abbr string_View string_view
abbr String_view string_view
abbr tempalte template
abbr typeanme typename
abbr unsigend unsigned
abbr unsinged unsigned
abbr vecotr vector
