name: pre-commit

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: pre-commit/action@v2.0.0
